version: 2
jobs:
  build:
    docker:
      - image: framgiaciteam/php:7.3

    steps:
      - checkout
      - run: cp .env.example .env

      # composer cache
      - restore_cache:
          keys:
            - vendor-v1-{{ checksum "composer.lock" }}
      - run: composer install
      - save_cache:
          key: vendor-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      # run
      - run:
          name: Generating app key
          command: |
            php artisan key:generate
      - run:
          name: Running test
          command: |
            phpcs --standard=Framgia --encoding=utf-8 app
      - run:
          name: Sending notification
          when: on_fail
          command: |
            if [[ true ]];  then
              curl -X POST -H "X-ChatWorkToken: $CHATWORK_TOKEN" -d \
                "body=[To:2611547]
                [info][title]Build $CIRCLE_BUILD_NUM - FAIL[/title]
                Repo: $CIRCLE_PROJECT_REPONAME
                Author: $CIRCLE_USERNAME
                Branch: $CIRCLE_BRANCH
                Build link: https://circleci.com/gh/dqhuy78/hblog-api/$CIRCLE_BUILD_NUM
                [/info]" \
                "https://api.chatwork.com/v2/rooms/$CHATWORK_ROOM_ID/messages"
            fi
      - run:
          name: Sending notification
          when: on_success
          command: |
            if [[ true ]];  then
              curl -X POST -H "X-ChatWorkToken: $CHATWORK_TOKEN" -d \
                "body=[To:2611547]
                [info][title]Build $CIRCLE_BUILD_NUM - SUCCESS[/title]
                Repo: $CIRCLE_PROJECT_REPONAME
                Author: $CIRCLE_USERNAME
                Branch: $CIRCLE_BRANCH
                Build link: https://circleci.com/gh/dqhuy78/hblog-api/$CIRCLE_BUILD_NUM
                [/info]" \
                "https://api.chatwork.com/v2/rooms/$CHATWORK_ROOM_ID/messages"
            fi
